spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: admin-server
            client-secret: DcV7fmokzrJXpoP7vaScRenrPFf1wvfu
            authorization-grant-type: client_credentials
            scope:
              - eureka
              - metrics
          login:
            provider: keycloak
            scope:
              - eureka
              - metrics
              - openid
            client-id: admin-server
            client-secret: DcV7fmokzrJXpoP7vaScRenrPFf1wvfu
        provider:
          keycloak:
            issuer-uri: http://0.0.0.1:9180/realms/cinema
            token-uri: http://0.0.0.1:9180/realms/cinema/protocol/openid-connect/token
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://0.0.0.1:9180/realms/cinema
          jwk-set-uri: http://0.0.0.1:9180/realms/cinema/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://0.0.0.1:8761/eureka/
    register-with-eureka: false
  instance:
    prefer-ip-address: true

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
          - metrics
  zipkin:
    tracing:
      endpoint: http://0.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.4