-- Статус бронирования
CREATE TYPE booking_status AS ENUM ('CREATED', 'PAID', 'CANCELED');

-- Бронирование
CREATE TABLE IF NOT EXISTS bookings
(
    -- Идентификатор
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Идентификатор пользователя
    user_id VARCHAR(36) NOT NULL,
    -- Идентификатор сеанса
    session_id BIGINT NOT NULL,
    -- Статус заказа
    status booking_status NOT NULL,
    -- Кто создал запись
    created_by VARCHAR(100) NOT NULL,
    -- Дата и время создания записи
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Кто обновил запись
    updated_by VARCHAR(100) NOT NULL,
    -- Дата и время обновления записи
    updated_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Места
CREATE TABLE IF NOT EXISTS booking_places
(
    -- Идентификатор
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Идентификатор бронирования
    booking_id BIGINT NOT NULL,
    -- Идентификатор места
    place_id BIGINT NOT NULL,
    -- Кто создал запись
    created_by VARCHAR(100) NOT NULL,
    -- Дата и время создания записи
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Кто обновил запись
    updated_by VARCHAR(100) NOT NULL,
    -- Дата и время обновления записи
    updated_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);