-- Страны
CREATE TABLE IF NOT EXISTS countries (
    -- Идентификатор
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Код страны
    code VARCHAR(3) UNIQUE NOT NULL,
    -- Наименование страны
    name VARCHAR(100) NOT NULL,
    -- Кто создал запись
    created_by VARCHAR(100) NOT NULL,
    -- Дата и время создания записи
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Кто обновил запись
    updated_by VARCHAR(100) NOT NULL,
    -- Дата и время обновления записи
    updated_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Участники фильмов
CREATE TABLE participants (
    -- Идентификатор
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Фамилия
    last_name VARCHAR(50) NOT NULL,
    -- Имя
    first_name VARCHAR(50) NOT NULL,
    -- Отчество
    middle_name VARCHAR(100),
    -- Кто создал запись
    created_by VARCHAR(100) NOT NULL,
    -- Дата и время создания записи
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Кто обновил запись
    updated_by VARCHAR(100) NOT NULL,
    -- Дата и время обновления записи
    updated_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)