services:
  psql_dictionary:
    container_name: psql_dictionary
    image: postgres:16
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dictionary_db
      PGDATA: /data/postgres
    volumes:
      - ./data/psql_dictionary:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - microservices-net

  psql_movie:
    container_name: psql_movie
    image: postgres:16
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: movie_db
      PGDATA: /data/postgres
    volumes:
      - ./data/psql_movie:/data/postgres
    ports:
      - "5436:5432"
    networks:
      - microservices-net

  psql_session:
    container_name: psql_session
    image: postgres:16
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: session_db
      PGDATA: /data/postgres
    volumes:
      - ./data/psql_session:/data/postgres
    ports:
      - "5437:5432"
    networks:
      - microservices-net

  psql_booking:
    container_name: psql_booking
    image: postgres:16
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: booking_db
      PGDATA: /data/postgres
    volumes:
      - ./data/psql_booking:/data/postgres
    ports:
      - "5438:5432"
    networks:
      - microservices-net

  psql_file:
    container_name: psql_file
    image: postgres:16
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: file_db
      PGDATA: /data/postgres
    volumes:
      - ./data/psql_file:/data/postgres
    ports:
      - "5439:5432"
    networks:
      - microservices-net

  psql_receipt:
    container_name: psql_receipt
    image: postgres:16
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: receipt_db
      PGDATA: /data/postgres
    volumes:
      - ./data/psql_receipt:/data/postgres
    ports:
      - "5440:5432"
    networks:
      - microservices-net

  psql_quartz:
    container_name: psql_quartz
    image: postgres:16
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: quartz_db
      PGDATA: /data/postgres
    volumes:
      - ./data/psql_quartz:/data/postgres
    ports:
      - "5441:5432"
    networks:
      - microservices-net

  psql_keycloak:
    container_name: psql_keycloak
    image: postgres:16
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: keycloak_db
    volumes:
      - ./data/psql_keycloak:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      - microservices-net
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-pass}

      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: developer
      KC_DB_PASSWORD: pass
      KC_DB_URL_HOST: psql_keycloak
      KC_DB_URL_DATABASE: keycloak_db
    ports:
      - "9180:8080"
    volumes:
      - ./data/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - psql_keycloak
    networks:
      - microservices-net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0.6-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - microservices-net

  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true