spring:
  flyway:
    locations: classpath:db/migration
    enabled: true
    clean-disabled: true
  cloud:
    config:
      enabled: false
    loadbalancer:
      enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: "info"
    dev.receipt: "debug"

keycloak:
  client-id: gateway-client
  client-secret: lax66b9pOJMmfBEG4e9A8AyKrzRISOSY

eureka:
  client:
    enabled: false

errors:
  booking:
    id-and-user-id:
      not-found: Бронирование с идентификатором %d для пользователя %s не найдено
  receipt:
    booking-id:
      not-found: Запись о квитанции с идентификатором бронирования %d не найдена
      already-exists: Запись о квитанции с идентификатором %d уже существует

rabbitmq:
  receipt:
    queue:
      creation: creation_receipt_queue
      update: update_receipt_queue
      update-status: update_status_receipt_queue
      delete: delete_receipt_queue
    exchange: exchange_receipt
    routing-key:
      creation: creation_receipt_routing_key
      update: update_receipt_routing_key
      update-status: update_status_receipt_routing_key
      delete: delete_receipt_routing_key
  notification:
    queue:
      creation: creation_notification_queue
      update: update_notification_queue
      update-status: update_status_notification_queue
      delete: delete_notification_queue
    exchange: exchange_notification
    routing-key:
      creation: creation_notification_routing_key
      update: update_notification_routing_key
      update-status: update_status_notification_routing_key
      delete: delete_notification_routing_key

currency:
  sign: ₽

url:
  booking: http://localhost:8151/api/v1/bookings
  user: http://localhost:8152/api/v1/users
  movie: http://localhost:8153/api/v1/movies

font:
  path: DejaVuSerif-Bold.ttf
