spring:
  flyway:
    locations: classpath:db/migration
    enabled: true
    clean-disabled: true
  cloud:
    config:
      enabled: false
    loadbalancer:
      enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: "info"
    dev.booking: "debug"

rabbitmq:
  receipt:
    queue:
      creation: creation_receipt_queue
      update: update_receipt_queue
      update-status: update_status_receipt_queue
      delete: delete_receipt_queue
    exchange: exchange_receipt
    routing-key:
      creation: creation_receipt_routing_key
      update: update_receipt_routing_key
      update-status: update_status_receipt_routing_key
      delete: delete_receipt_routing_key
  booking:
    queue:
      check-by-session: check_by_session_booking_queue
    exchange: exchange_booking
    routing-key:
      check-by-session: check_by_session_booking_routing_key
  session:
    queue:
      place:
        update-available: update_available_session_place_queue
    exchange: exchange_session
    routing-key:
      place:
        update-available: update_available_session_place_routing_key

keycloak:
  client-id: gateway-client
  client-secret: lax66b9pOJMmfBEG4e9A8AyKrzRISOSY

eureka:
  client:
    enabled: false

url:
  movie: http://localhost:8141/api/v1/movies
  place: http://localhost:8142/api/v1/places
  session: http://localhost:8143/api/v1/sessions
  user: http://localhost:8144/api/v1/users

errors:
  booking:
    id:
      not-found: Бронирование с идентификатором %d не найдено
    user-id:
      bad-request: Идентификатор пользователя не может быть пустым
    id-user-id:
      not-found: Бронирование с идентификатором %d для пользователя %s не найдено
    id-status:
      already-exists: Статус бронирования %s у брони с идентификатором %d уже существует
      bad-request: Невозможно обновить отмененную бронь
    status:
      bad-request: Невозможно создать отмененную бронь
    places:
      already-exists: Место с идентификатором %d занято
      bad-request: Место с идентификатором %d не относится к сеансу с идентификатором %d
    session:
      time-end:
        bad-request: Бронирование мест невозможно, т.к. сеанс %s в зале %d закончен
      available:
        bad-request: Сеанс с идентификатором %d недоступен для бронирования