-- Формат фильма
CREATE TYPE movie_format AS ENUM ('TWO_D', 'THREE_D');

-- Сеансы
CREATE TABLE IF NOT EXISTS sessions
(
    -- Идентификатор
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Идентификатор фильма
    movie_id BIGINT NOT NULL,
    -- Формат фильма
    format movie_format NOT NULL,
    -- Зал
    hall INT NOT NULL,
    -- Дата и время сеанса
    date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Доступен ли сеанс
    available BOOLEAN NOT NULL DEFAULT FALSE,
    -- Кто создал запись
    created_by VARCHAR(100) NOT NULL,
    -- Дата и время создания записи
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Кто обновил запись
    updated_by VARCHAR(100) NOT NULL,
    -- Дата и время обновления записи
    updated_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Места
CREATE TABLE IF NOT EXISTS places
(
    -- Идентификатор
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Идентификатор сеанса
    session_id BIGINT NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    -- Ряд
    row INT NOT NULL,
    -- Номер места
    number INT NOT NULL,
    -- Цена за место
    price NUMERIC NOT NULL ,
    -- Доступно для бронирования
    available BOOLEAN NOT NULL DEFAULT FALSE,
    -- Кто создал запись
    created_by VARCHAR(100) NOT NULL,
    -- Дата и время создания записи
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Кто обновил запись
    updated_by VARCHAR(100) NOT NULL,
    -- Дата и время обновления записи
    updated_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);