INSERT INTO movies(name, description, duration, year, rating, rental, created_by, updated_by) VALUES
('Перевозчик душ', 'Энн и Патрик после ночной прогулки в расстроенных чувствах садятся в черное такси, водителем которого оказывается добродушный и болтливый мужчина. Пара переживает не лучший этап в отношениях, поэтому неохотно поддерживает диалог. Неожиданно вместо дома они оказываются запертыми в машине на пустынном участке дороги, населенном привидениями. Чтобы выжить, паре необходимо выяснить личность загадочного таксиста и его мотивы', 98, 2024, 'EIGHTEEN', true, 'flyway', 'flyway'),
('Приключения Паддингтона 3', 'Паддингтон, ставший полноправным членом семьи Браунов и гражданином Великобритании, отправляется в гости к тетушке Люси на свою далекую родину — в Перу', 114, 2024, 'SIX', true, 'flyway', 'flyway');

INSERT INTO genres(name, created_by, updated_by) VALUES
('Комедии', 'flyway', 'flyway'),
('Мультфильмы', 'flyway', 'flyway'),
('Ужасы', 'flyway', 'flyway'),
('Фантастика', 'flyway', 'flyway'),
('Триллеры', 'flyway', 'flyway'),
('Боевики', 'flyway', 'flyway'),
('Мелодрамы', 'flyway', 'flyway'),
('Детективы', 'flyway', 'flyway'),
('Приключения', 'flyway', 'flyway'),
('Фэнтези', 'flyway', 'flyway'),
('Военные', 'flyway', 'flyway'),
('Семейный', 'flyway', 'flyway'),
('Аниме', 'flyway', 'flyway'),
('Исторические', 'flyway', 'flyway'),
('Драмы', 'flyway', 'flyway'),
('Документальные', 'flyway', 'flyway'),
('Детские', 'flyway', 'flyway'),
('Криминал', 'flyway', 'flyway'),
('Биография', 'flyway', 'flyway'),
('Вестерны', 'flyway', 'flyway'),
('Нуар', 'flyway', 'flyway'),
('Спортивные', 'flyway', 'flyway'),
('Реальное ТВ', 'flyway', 'flyway'),
('Короткометражки', 'flyway', 'flyway'),
('Музыкальные', 'flyway', 'flyway'),
('Мюзиклы', 'flyway', 'flyway'),
('Ток-шоу', 'flyway', 'flyway'),
('Игры', 'flyway', 'flyway');