spring:
  datasource:
    url: jdbc:postgresql://0.0.0.1:5438/booking_db
    username: developer
    password: ENC(3aSnLZWuNviOXePzCg9BOq2OF+3PrRQ6L7H4aIeHbo0UK+3HTr4UTJWK/HS0UTSj)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: gateway-client
            client-secret: ENC(yT2oF4I9HtGlw6Pv0yCee5YjPp/DiehEm5ci17E8v9J9KTEBH6VZhzFGKuaBPKUOqVcdYp9PoQRL5/rkj/ZIRLlymzfRdIFrWyUQg9F8HKM=)
            authorization-grant-type: client_credentials
            scope:
              - metrics
              - eureka
              - config
        provider:
          keycloak:
            issuer-uri: http://0.0.0.1:9180/realms/cinema
            token-uri: http://0.0.0.1:9180/realms/cinema/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://0.0.0.1:9180/realms/cinema
          jwk-set-uri: http://0.0.0.1:9180/realms/cinema/protocol/openid-connect/certs
  rabbitmq:
    host: 0.0.0.1
    port: 5672
    username: admin
    password: ENC(ORcESJhoOIBIMxZKrknWqIUo0y4KajrY9n48MDeiT7fwL+sNnYh8gPvVYaLhUFeH)

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://0.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
          - metrics
  zipkin:
    tracing:
      endpoint: http://0.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.4

logging:
  level:
    root: "info"
    dev.booking: "debug"

url:
  movie: lb://movie-service/api/v1/movies
  place: lb://session-service/api/v1/places
  session: lb://session-service/api/v1/sessions
  user: lb://user-service/api/v1/users

swagger:
  url: http://0.0.0.1:9000