server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations/{application}