spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: config-server
            client-secret: OnzxLcAxbHYm3ZTBAMhHqVyGHkHR9beN
            authorization-grant-type: client_credentials
            scope:
              - openid
              - metrics
              - config
              - eureka
        provider:
          keycloak:
            issuer-uri: http://0.0.0.1:9180/realms/cinema
            token-uri: http://0.0.0.1:9180/realms/cinema/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://0.0.0.1:9180/realms/cinema
          jwk-set-uri: http://0.0.0.1:9180/realms/cinema/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://0.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
          - metrics
  zipkin:
    tracing:
      endpoint: http://0.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.4